### ISSUE TITLE
any idea what's going on?

### ISSUE THREAD

**Issue by aiskingstud** [charmoniumQ/antlr4-python-grun#2]
I tried: pygrun parse ./barebones.g test

And got this output:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python39\Scripts\pygrun.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python39\Lib\site-packages\antlr4_grun\cli.py", line 58, in main
    app()
  File "C:\Program Files\Python39\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python39\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python39\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python39\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python39\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python39\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python39\Lib\site-packages\typer\main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python39\Lib\site-packages\antlr4_grun\cli.py", line 53, in parse
    root = lib.parse(grammar, initial_rule, input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python39\Lib\site-packages\antlr4_grun\lib.py", line 145, in parse
    Lexer, Parser = get_lexer_parser(grammar)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python39\Lib\site-packages\antlr4_grun\lib.py", line 111, in get_lexer_parser
    build_dir = compile(grammar_path)
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python39\Lib\site-packages\antlr4_grun\lib.py", line 93, in compile
    subprocess.run(
  File "C:\Program Files\Python39\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python39\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python39\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by charmoniumQ** [comment]
Do you have Java installed? Test this by going to `CMD.EXE` and typing  `java --version`.
